---
openbao_version: "2.6.2"
openbao_files_dir: "{{ playbook_dir }}/files"
openbao_verify_checksum: true

openbao_arch_map:
  x86_64: amd64
  aarch64: arm64
openbao_arch: "{{ openbao_arch_map[ansible_architecture] | default(ansible_architecture) }}"
openbao_package_ext: "{{ 'deb' if ansible_os_family == 'Debian' else 'rpm' }}"
openbao_package_filename: "openbao_{{ openbao_version }}_linux_{{ openbao_arch }}.{{ openbao_package_ext }}"

openbao_bind_host: "{{ ansible_host | default(inventory_hostname, true) }}"
openbao_api_addr: "https://{{ openbao_bind_host }}:8200"
openbao_cluster_addr: "https://{{ openbao_bind_host }}:8201"
openbao_ui: true
openbao_node_id: "{{ inventory_hostname }}"

openbao_user: openbao
openbao_group: openbao
openbao_config_dir: /etc/openbao
openbao_config_file: /etc/openbao/openbao.hcl
openbao_tls_dir: /etc/openbao/tls
openbao_data_dir: /opt/openbao/data

openbao_tls_cert_src: "{{ openbao_files_dir }}/tls.crt"
openbao_tls_key_src: "{{ openbao_files_dir }}/tls.key"
